// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NHLApp.Infrastructure.Data;

#nullable disable

namespace NHLApp.Infrastructure.Migrations
{
    [DbContext(typeof(NHLAppDbContext))]
    [Migration("20260829201642_FIX_NULLABLE_PROPERTIES")]
    partial class FIX_NULLABLE_PROPERTIES
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NHLApp.Domain.Entities.DraftDetail", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("OverallPick")
                        .HasColumnType("int");

                    b.Property<int?>("PickInRound")
                        .HasColumnType("int");

                    b.Property<int?>("Round")
                        .HasColumnType("int");

                    b.Property<string>("TeamAbbrev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("DraftDetail");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Franchise", b =>
                {
                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FranchiseId");

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int?>("AwaySog")
                        .HasColumnType("int");

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<string>("GameDate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GameScheduleState")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GameState")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("GameType")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int?>("HomeSog")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<string>("LastPeriodType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("LimitedScoring")
                        .HasColumnType("bit");

                    b.Property<bool?>("OtInUse")
                        .HasColumnType("bit");

                    b.Property<int?>("OtPeriods")
                        .HasColumnType("int");

                    b.Property<int?>("RegPeriods")
                        .HasColumnType("int");

                    b.Property<int?>("Season")
                        .HasColumnType("int");

                    b.Property<bool?>("ShootoutInUse")
                        .HasColumnType("bit");

                    b.Property<string>("SpecialEventName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SpecialEventParentId")
                        .HasColumnType("int");

                    b.Property<string>("StartTimeUTC")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<bool?>("Tie")
                        .HasColumnType("bit");

                    b.Property<string>("VenueDefault")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("VenueLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.GamePlay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Assist1PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("Assist1PlayerTotal")
                        .HasColumnType("int");

                    b.Property<int?>("Assist2PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("Assist2PlayerTotal")
                        .HasColumnType("int");

                    b.Property<int?>("Assist3PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("Assist3PlayerTotal")
                        .HasColumnType("int");

                    b.Property<int?>("AwaySOG")
                        .HasColumnType("int");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int?>("BlockingPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("CommittedByPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("DetailsDescKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailsTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DrawnByPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("EventOwnerTeamId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("GoalInGame")
                        .HasColumnType("int");

                    b.Property<int?>("GoalieInNetId")
                        .HasColumnType("int");

                    b.Property<int?>("HitteePlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("HittingPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeSOG")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeamDefendingSide")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("LosingPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltyDuration")
                        .HasColumnType("int");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("int");

                    b.Property<string>("PeriodType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ScoringPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("ScoringPlayerTotal")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ServedByPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("ShootingPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("ShotType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SituationCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TimeInPeriod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TimeRemaining")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TypeCode")
                        .HasColumnType("int");

                    b.Property<string>("TypeDescKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("WinningPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("XCoord")
                        .HasColumnType("int");

                    b.Property<int?>("YCoord")
                        .HasColumnType("int");

                    b.Property<string>("ZoneCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "EventId")
                        .IsUnique();

                    b.ToTable("GamePlays");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.GoalieGameStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Decision")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("EvenStrengthGoalsAgainst")
                        .HasColumnType("int");

                    b.Property<string>("EvenStrengthShotsAgainst")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("Pim")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PowerPlayGoalsAgainst")
                        .HasColumnType("int");

                    b.Property<string>("PowerPlayShotsAgainst")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<float>("SavePctg")
                        .HasColumnType("real");

                    b.Property<string>("SaveShotsAgainst")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Saves")
                        .HasColumnType("int");

                    b.Property<int>("ShorthandedGoalsAgainst")
                        .HasColumnType("int");

                    b.Property<string>("ShorthandedShotsAgainst")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("ShotsAgainst")
                        .HasColumnType("int");

                    b.Property<bool>("Starter")
                        .HasColumnType("bit");

                    b.Property<int>("SweaterNumber")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Toi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "PlayerId", "TeamId")
                        .IsUnique();

                    b.ToTable("GoalieGameStats");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("BirthCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthStateProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentTeamAbbrev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentTeamId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullTeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Headshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HeightInCentimeters")
                        .HasColumnType("int");

                    b.Property<int?>("HeightInInches")
                        .HasColumnType("int");

                    b.Property<string>("HeroImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerSlug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShootsCatches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SweaterNumber")
                        .HasColumnType("int");

                    b.Property<string>("TeamCommonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamPlaceNameWithPreposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeightInKilograms")
                        .HasColumnType("int");

                    b.Property<int?>("WeightInPounds")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.PlayerAwards", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("TrophyId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "TrophyId", "SeasonId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TrophyId");

                    b.ToTable("PlayerAwards");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.PlayerGameStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("BlockedShots")
                        .HasColumnType("int");

                    b.Property<float>("FaceoffWinningPctg")
                        .HasColumnType("real");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Giveaways")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<int>("Hits")
                        .HasColumnType("int");

                    b.Property<int>("Pim")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PlusMinus")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("PowerPlayGoals")
                        .HasColumnType("int");

                    b.Property<int>("Shifts")
                        .HasColumnType("int");

                    b.Property<int>("Sog")
                        .HasColumnType("int");

                    b.Property<int>("SweaterNumber")
                        .HasColumnType("int");

                    b.Property<int>("Takeaways")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Toi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "PlayerId", "TeamId")
                        .IsUnique();

                    b.ToTable("PlayerGameStats");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.RawApiResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RawApiResponses");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("SeasonId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.SeasonTotal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Assists")
                        .HasColumnType("int");

                    b.Property<string>("AvgToi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("FaceoffWinningPctg")
                        .HasColumnType("real");

                    b.Property<int?>("GameTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("GameWinningGoals")
                        .HasColumnType("int");

                    b.Property<int?>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int?>("Goals")
                        .HasColumnType("int");

                    b.Property<string>("LeagueAbbrev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OtGoals")
                        .HasColumnType("int");

                    b.Property<int?>("Pim")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("PlusMinus")
                        .HasColumnType("int");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("PowerPlayGoals")
                        .HasColumnType("int");

                    b.Property<int?>("PowerPlayPoints")
                        .HasColumnType("int");

                    b.Property<int?>("Season")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<float?>("ShootingPctg")
                        .HasColumnType("real");

                    b.Property<int?>("ShorthandedGoals")
                        .HasColumnType("int");

                    b.Property<int?>("ShorthandedPoints")
                        .HasColumnType("int");

                    b.Property<int?>("Shots")
                        .HasColumnType("int");

                    b.Property<string>("TeamCommonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamPlaceNameWithPreposition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("SeasonTotals");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("RawTriCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId", "SeasonId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.TeamRosters", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("TeamId", "PlayerId", "SeasonId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId", "SeasonId");

                    b.ToTable("TeamRosters");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Trophy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trophies");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.DraftDetail", b =>
                {
                    b.HasOne("NHLApp.Domain.Entities.Player", "Player")
                        .WithOne("DraftDetail")
                        .HasForeignKey("NHLApp.Domain.Entities.DraftDetail", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.GamePlay", b =>
                {
                    b.HasOne("NHLApp.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.GoalieGameStat", b =>
                {
                    b.HasOne("NHLApp.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.PlayerAwards", b =>
                {
                    b.HasOne("NHLApp.Domain.Entities.Player", "Player")
                        .WithMany("PlayerAwards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NHLApp.Domain.Entities.Season", "Season")
                        .WithMany("Awards")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NHLApp.Domain.Entities.Trophy", "Trophy")
                        .WithMany("Awards")
                        .HasForeignKey("TrophyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Season");

                    b.Navigation("Trophy");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.PlayerGameStat", b =>
                {
                    b.HasOne("NHLApp.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.SeasonTotal", b =>
                {
                    b.HasOne("NHLApp.Domain.Entities.Player", "Player")
                        .WithMany("SeasonTotal")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Team", b =>
                {
                    b.HasOne("NHLApp.Domain.Entities.Franchise", "Franchise")
                        .WithMany("Teams")
                        .HasForeignKey("FranchiseId");

                    b.HasOne("NHLApp.Domain.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.TeamRosters", b =>
                {
                    b.HasOne("NHLApp.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NHLApp.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId", "SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Franchise", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Player", b =>
                {
                    b.Navigation("DraftDetail");

                    b.Navigation("PlayerAwards");

                    b.Navigation("SeasonTotal");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Season", b =>
                {
                    b.Navigation("Awards");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Trophy", b =>
                {
                    b.Navigation("Awards");
                });
#pragma warning restore 612, 618
        }
    }
}
