// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NHLApp.Infrastructure.Data;

#nullable disable

namespace NHLApp.Infrastructure.Migrations
{
    [DbContext(typeof(NHLAppDbContext))]
    [Migration("20260806154923_FixGameId")]
    partial class FixGameId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NHLApp.Domain.Entities.DraftDetail", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("OverallPick")
                        .HasColumnType("int");

                    b.Property<int?>("PickInRound")
                        .HasColumnType("int");

                    b.Property<int?>("Round")
                        .HasColumnType("int");

                    b.Property<string>("TeamAbbrev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("DraftDetail");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Franchise", b =>
                {
                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FranchiseId");

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Game", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("BirthCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthStateProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentTeamAbbrev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentTeamId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullTeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Headshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HeightInCentimeters")
                        .HasColumnType("int");

                    b.Property<int?>("HeightInInches")
                        .HasColumnType("int");

                    b.Property<string>("HeroImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerSlug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShootsCatches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SweaterNumber")
                        .HasColumnType("int");

                    b.Property<string>("TeamCommonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamPlaceNameWithPreposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeightInKilograms")
                        .HasColumnType("int");

                    b.Property<int?>("WeightInPounds")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.PlayerAwards", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("TrophyId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "TrophyId", "SeasonId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TrophyId");

                    b.ToTable("PlayerAwards");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.RawApiResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RawApiResponses");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("SeasonId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.SeasonTotal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Assists")
                        .HasColumnType("int");

                    b.Property<string>("AvgToi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("FaceoffWinningPctg")
                        .HasColumnType("real");

                    b.Property<int?>("GameTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("GameWinningGoals")
                        .HasColumnType("int");

                    b.Property<int?>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int?>("Goals")
                        .HasColumnType("int");

                    b.Property<string>("LeagueAbbrev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OtGoals")
                        .HasColumnType("int");

                    b.Property<int?>("Pim")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("PlusMinus")
                        .HasColumnType("int");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("PowerPlayGoals")
                        .HasColumnType("int");

                    b.Property<int?>("PowerPlayPoints")
                        .HasColumnType("int");

                    b.Property<int?>("Season")
                        .HasColumnType("int");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<float?>("ShootingPctg")
                        .HasColumnType("real");

                    b.Property<int?>("ShorthandedGoals")
                        .HasColumnType("int");

                    b.Property<int?>("ShorthandedPoints")
                        .HasColumnType("int");

                    b.Property<int?>("Shots")
                        .HasColumnType("int");

                    b.Property<string>("TeamCommonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamPlaceNameWithPreposition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("SeasonTotals");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("RawTriCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId", "SeasonId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.TeamRosters", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("TeamId", "PlayerId", "SeasonId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId", "SeasonId");

                    b.ToTable("TeamRosters");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Trophy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trophies");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.DraftDetail", b =>
                {
                    b.HasOne("NHLApp.Domain.Entities.Player", "Player")
                        .WithOne("DraftDetail")
                        .HasForeignKey("NHLApp.Domain.Entities.DraftDetail", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.PlayerAwards", b =>
                {
                    b.HasOne("NHLApp.Domain.Entities.Player", "Player")
                        .WithMany("PlayerAwards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NHLApp.Domain.Entities.Season", "Season")
                        .WithMany("Awards")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NHLApp.Domain.Entities.Trophy", "Trophy")
                        .WithMany("Awards")
                        .HasForeignKey("TrophyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Season");

                    b.Navigation("Trophy");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.SeasonTotal", b =>
                {
                    b.HasOne("NHLApp.Domain.Entities.Player", "Player")
                        .WithMany("SeasonTotal")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Team", b =>
                {
                    b.HasOne("NHLApp.Domain.Entities.Franchise", "Franchise")
                        .WithMany("Teams")
                        .HasForeignKey("FranchiseId");

                    b.HasOne("NHLApp.Domain.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.TeamRosters", b =>
                {
                    b.HasOne("NHLApp.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NHLApp.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId", "SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Franchise", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Player", b =>
                {
                    b.Navigation("DraftDetail");

                    b.Navigation("PlayerAwards");

                    b.Navigation("SeasonTotal");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Season", b =>
                {
                    b.Navigation("Awards");
                });

            modelBuilder.Entity("NHLApp.Domain.Entities.Trophy", b =>
                {
                    b.Navigation("Awards");
                });
#pragma warning restore 612, 618
        }
    }
}
